---
- name: Install Apache package 
  hosts: node* # "{{ rhel_inventory_group | default(all) }}"
  become: true
  tasks:
    - name: Task 1 - install httpd package 
      ansible.builtin.dnf:
        name: 
          - httpd
          - firewalld
        state: latest
