---
- name: Install Apache package 
  hosts: "{{ rhel_inventory_group | default(all) }}"
  become: true
  tasks:
    - name: Task 1 - install httpd package 
      ansible.builtin.dnf:
        name: httpd
        state: latest
