---
- name: Enable & Startup Apache service 
  hosts: node* # "{{ rhel_inventory_group | default(all) }}"
  become: true
  tasks:
    - name: task 2 - enable & start apache service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
