---
- name: Permit traffic through firewall
  hosts: "{{ rhel_inventory_group | default(all) }}"
  become: true
  tasks:
    - name: Task 3 - allow traffic in firewall
      ansible.posix.firewalld:
        service: "{{ item }}"
        state: enabled
        permanent: true
        immediate: true
      loop:
        - http
        - https
