---
- name: Create user Ansible
  hosts: rhel8
  become: true
  tasks:
    - name: Task 1 - Create group Admins
      ansible.builtin.group:
        name: admins
        state: present
        gid: 10001
        
    - name: Task 2 - Create user ansible
      ansible.builtin.user:
        name: ansible
        uid: 2001
        shell: /bin/bash
        groups: 
          - admins
          - wheel
        append: yes
        password: "{{ 'redhat' | password_hash('sha512') }}"
        update_password: on_create
        
    - name: Task 3 - Configure SUDO 
      ansible.builtin.copy:
        dest: /etc/sudoers.d/ansible
        content: "ansible ALL=(ALL) NOPASSWD: ALL"
        mode: '0440'
        validate: /usr/sbin/visudo -cf %s

    - name: Task 4 - Configure authorized key
      ansible.posix.authorized_key:
        user: ansible
        state: present 
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF0PYuKKID3vri8tYR+3vf4sWxBBPHapPIb4z4dpC+1Q ansible@example.com"

        
        
        
        
