---
- name: Create user through variable
  hosts: rhel8
  become: true
  vars:
    username: 
    password: 
    uid: 
    password_max: 
  tasks:
    - name: Task 1 - Create user through vairables 
      ansible.builtin.user:
        name: "{{ username | default('admin01') }}"
        uid: "{{ uid | default('1001') }}"
        shell: /bin/bash
        groups: 
          - admins
          - wheel
        append: yes
        password: "{{ password | default('redhat123') | password_hash('sha512') }}"
        update_password: on_create
        password_expire_max: "{{ password_max | default('90') }}"
