---
- name: Display managed hosts facts
  hosts: "{{ rhel_inventory_group | default(all) }}"
  become: false
  gather_facts: true
  tasks:
    #- name: Tarea 1: Modulo setup 
     # ansible.builtin.setup:
      #register: facts

    - name: Display all variables
      ansible.builtin.debug:
        var: ansible_facts
        

    - name: Display specific variables  
      ansible.builtin.debug:
        msg: > # |
          The default IPv4 address of {{ ansible_facts['fqdn'] }} 
          is {{ ansible_facts['default_ipv4']['address'] }}

    - name: Collect hardware specific group
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - '!min'
          - 'network'
          - '!mounts'
      register: facts

    - name: Display hardware specific group
      ansible.builtin.debug:
        msg: Tha facts are {{ facts }}
          
