---
- name: Harden SSH server with loop
  hosts: all
  become: yes
  vars:
    port: 22
    sshd_logon_banner: |
      ###############################################################################
      #                   ___    _   _______ ________  __    ______                 #
      #                  /   |  / | / / ___//  _/ __ )/ /   / ____/                 #
      #                 / /| | /  |/ /\__ \ / // __  / /   / __/                    #
      #                / ___ |/ /|  /___/ // // /_/ / /___/ /___                    #
      #               /_/  |_/_/ |_//____/___/_____/_____/_____/                    #
      #                                                                             #
      #                             AUTHORIZED USE ONLY                             #
      #                                                                             #
      #                           THIS SYSTEM IS MONITORED                          #
      #                                                                             #
      #                     UNAUTHORIZED USE STRICTLY PROHIBITED                    #
      ###############################################################################
    sshd_config_lines:
      - regexp: ^#?PermitEmptyPasswords
        line: PermitEmptyPasswords no

      - regexp: ^#?PasswordAuthentication
        line: PasswordAuthentication yes
        
      - regexp: (?i)^#?port
        line: Port 22
                      
      - regexp: (?i)^#?x11forwarding
        line: X11Forwarding yes
                      
      - regexp: ^#?Banner
        line: Banner /etc/issue
                      
      - regexp: ^#?permituserenvironment
        line: permituserenvironment no
                      
      - regexp: (?i)^#?Ciphers
        line: Ciphers aes128-ctr,aes192-ctr,aes256-ctr
                      
      - regexp: ^#?ClientAliveInterval
        line: ClientAliveInterval 600
                      
      - regexp: ^#?IgnoreRhosts
        line: IgnoreRhosts yes
                      
      - regexp: ^#?PermitRootLogin
        line: PermitRootLogin no
                      
  tasks:              
    - name: Harden ssh settings
      ansible.builtin.lineinfile:
        state: present
        dest: /etc/ssh/sshd_config
        line: "{{ item.line }}"
        regexp: "{{ item.regexp }}"
        validate: /usr/sbin/sshd -tf %s
      loop: "{{ sshd_config_lines }}"
      notify: restart sshd
                      
    - name: Copy ssh logon banner
      ansible.builtin.copy:
        content: "{{ sshd_logon_banner }}"
        dest: "{{ item }}"
        owner: root   
        group: root   
        mode: 0644    
      loop:           
          - /etc/issue
          - /etc/issue.net
    
    - name: Allow sshd to listen on tcp port 
      ansible.builtin.command:
        cmd: "semanage port -a -t ssh_port_t -p tcp {{ port }}"
      ignore_errors: true
      
    - name: Permit traffic in public zone on port {{ port }}/tcp
      ansible.posix.firewalld:
        port: "{{ port }}/tcp"
        permanent: true
        immediate: true
        state: enabled     
  handlers:
    - name: restart sshd
      ansible.builtin.service:
        name: sshd
        state: restarted
