---
- name: Install HTTPD package
  hosts: "{{ rhel_inventory_group | default(all) }}"
  become: true
  tasks:
    - name: Task 1 - install httpd package
      ansible.builtin.dnf:
        name: httpd
        state: latest

    - name: Task 2 - Create index.html file
      ansible.builtin.copy:
        content: "Welcome to {{ ansible_hostname }} server!\n"
        dest: /var/www/html/index.html

    - name: Task 3 - enable & start up httpd service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true 

    - name: Task 4 - Allow traffic to service httpd 
      ansible.posix.firewalld:
        service: "{{ item }}"
        state: enabled
        #zone: public
        permanent: true
        immediate: true
      loop:
        - https
        - http
    
