---
- name: Update operating system
  hosts: all
  become: true 
  tasks: 
    - name: task1 - Update OS
      ansible.builtin.dnf:
        name: "*"
        state: latest
    - name: task2 - Reboot the VMs and wait 120s to boot up.
      ansible.builtin.reboot:
        reboot_timeout: 120    
