---
- name: Update operating system
  hosts: "{{ rhel_inventory_group | default(all) }}"
  become: true 
  tasks: 
    - name: Update packages on RedHat/Centos
      ansible.builtin.dnf:
        name: "*"
        state: latest
      when: ansible_facts['os_family'] == "RedHat"  
        
    - name: Update packages on Debian/Ubuntu
      ansible.builtin.apt:
        name: "*"
        state: latest
      when: ansible_facts['os_family'] == "Debian"
      
    - name: Reboot the VMs and wait 120s to boot up.
      ansible.builtin.reboot:
        reboot_timeout: 120    
